### ISSUE TITLE
On/Off or Impulse Issue

### ISSUE THREAD

**Issue by xUborka** [xUborka/pytreadmill#3]
On/Off or Impulse does not turn off

**Comment by tabzsi** [comment]
Never happens for ON signal, only for OFF signal. Issue does not occur during automatic (pos. based) triggering.

**Comment by T4psi** [comment]
Issue does not occur during recording.

**Comment by T4psi** [comment]
Based on hardware test (LED connected on port output), the OFF signal goes out but the port turns back ON immediately. It can be seen by a short blink of the LED.

**Comment by T4psi** [comment]
When I clicked the button to turn off the port, OFF and ON signal was sent sequentially to the hardware (last two rows). This only happens occasionally.

**Comment by xUborka** [comment]
Fixed, will be merged to main tomorrow (after a short cleanup session)
